Importing all libraries

In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
import keras

In [2]:
tf.__version__

'2.13.0'

Importing datasets

In [3]:
data = pd.read_excel("Folds5x2_pp.xlsx")
x = data.iloc[:,:-1]
y = data.iloc[:,-1]

In [4]:
data.head(3)

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56

In [5]:
x

AT      V       AP     RH
0     14.96  41.76  1024.07  73.17
1     25.18  62.96  1020.04  59.08
2      5.11  39.40  1012.16  92.14
3     20.86  57.32  1010.24  76.64
4     10.82  37.50  1009.23  96.62
...     ...    ...      ...    ...
9563  16.65  49.69  1014.01  91.00
9564  13.19  39.18  1023.67  66.78
9565  31.32  74.33  1012.92  36.48
9566  24.48  69.45  1013.86  62.39
9567  21.60  62.52  1017.23  67.87

[9568 rows x 4 columns]

In [6]:
y

0       463.26
1       444.37
2       488.56
3       446.48
4       473.90
         ...  
9563    460.03
9564    469.62
9565    429.57
9566    435.74
9567    453.28
Name: PE, Length: 9568, dtype: float64

 Spliting data into training and testing

In [7]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [8]:
x_train.shape

(7654, 4)

In [9]:
x_test.shape

(1914, 4)

In [10]:
y_test.shape

(1914,)

In [11]:
y_train.shape

(7654,)

Building the ANN

In [12]:
ann = tf.keras.models.Sequential()

adding input and 1st hidden  layers

In [13]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [14]:
ann

adding 2nd hidden  layers

In [15]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

adding output layer

In [16]:
ann.add(tf.keras.layers.Dense(units=1))

Compiling the ANN

In [17]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

Training the ANN model on the Training set

In [18]:
ann.fit(x_train,y_train,batch_size=32,epochs=50)

Epoch 1/50
240/240 [==============================] - 2s 3ms/step - loss: 2816.8423
Epoch 2/50
240/240 [==============================] - 1s 2ms/step - loss: 692.9312
Epoch 3/50
240/240 [==============================] - 1s 2ms/step - loss: 601.1458
Epoch 4/50
240/240 [==============================] - 0s 2ms/step - loss: 505.4196
Epoch 5/50
240/240 [==============================] - 1s 2ms/step - loss: 415.5223
Epoch 6/50
240/240 [==============================] - 1s 2ms/step - loss: 333.1859
Epoch 7/50
240/240 [==============================] - 1s 2ms/step - loss: 262.1137
Epoch 8/50
240/240 [==============================] - 1s 2ms/step - loss: 200.0932
Epoch 9/50
240/240 [==============================] - 1s 2ms/step - loss: 150.6160
Epoch 10/50
240/240 [==============================] - 1s 2ms/step - loss: 111.9784
Epoch 11/50
240/240 [==============================] - 1s 2ms/step - loss: 83.8315
Epoch 12/50
240/240 [==============================] - 1s 2ms/step - loss: 63.8716
Ep

Predicting the results of the Test set

In [31]:
y_pred = ann.predict(x_test)
y_pred

60/60 [==============================] - 0s 2ms/step


array([[430.03],
       [461.33],
       [464.93],
       ...,
       [471.98],
       [439.12],
       [458.2 ]], dtype=float32)

In [50]:
y_test = y_test.reshape(len(y_test),1)
y_test

array([[431.23],
       [460.01],
       [461.14],
       ...,
       [473.26],
       [438.  ],
       [463.28]])

In [55]:
np.concatenate((y_pred,y_test),1)

array([[430.03, 431.23],
       [461.33, 460.01],
       [464.93, 461.14],
       ...,
       [471.98, 473.26],
       [439.12, 438.  ],
       [458.2 , 463.28]])