## Using power plant data, based upon temperature,volume,pressure and humidity predicted energy 

### Importing all libraries

In [2]:
import pandas as pd
import numpy as np
import tensorflow as tf
import keras

In [3]:
tf.__version__   # Checking tensorflow version

'2.13.0'

## Importing dataset

In [4]:
data = pd.read_excel("Folds5x2_pp.xlsx")

In [5]:
data.head(3)

AT      V       AP     RH      PE
0  14.96  41.76  1024.07  73.17  463.26
1  25.18  62.96  1020.04  59.08  444.37
2   5.11  39.40  1012.16  92.14  488.56

## Separating data into dependent and independent variable

In [6]:
x = data.iloc[:,:-1].values
y = data.iloc[:,-1].values

In [7]:
x

array([[  14.96,   41.76, 1024.07,   73.17],
       [  25.18,   62.96, 1020.04,   59.08],
       [   5.11,   39.4 , 1012.16,   92.14],
       ...,
       [  31.32,   74.33, 1012.92,   36.48],
       [  24.48,   69.45, 1013.86,   62.39],
       [  21.6 ,   62.52, 1017.23,   67.87]])

In [8]:
y

array([463.26, 444.37, 488.56, ..., 429.57, 435.74, 453.28])

 ## Spliting data into training and testing

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [10]:
x_train.shape

(7654, 4)

In [11]:
x_test.shape

(1914, 4)

In [12]:
y_test.shape

(1914,)

In [13]:
y_train.shape

(7654,)

## Building the ANN

In [14]:
ann = tf.keras.models.Sequential()

## adding input and 1st hidden  layers

In [15]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

In [16]:
ann

## Adding 2nd hidden  layers

In [17]:
ann.add(tf.keras.layers.Dense(units=6,activation='relu'))

## Adding output layer

In [18]:
ann.add(tf.keras.layers.Dense(units=1))

## Compiling the ANN

In [19]:
ann.compile(optimizer = 'adam', loss = 'mean_squared_error')

## Training the ANN model on the Training set

In [20]:
ann.fit(x_train,y_train,batch_size=32,epochs=50)

Epoch 1/50
240/240 [==============================] - 2s 3ms/step - loss: 788.4733
Epoch 2/50
240/240 [==============================] - 1s 3ms/step - loss: 70.2796
Epoch 3/50
240/240 [==============================] - 1s 3ms/step - loss: 64.6112
Epoch 4/50
240/240 [==============================] - 1s 2ms/step - loss: 58.9020
Epoch 5/50
240/240 [==============================] - 1s 3ms/step - loss: 53.6695
Epoch 6/50
240/240 [==============================] - 1s 3ms/step - loss: 49.0780
Epoch 7/50
240/240 [==============================] - 1s 3ms/step - loss: 45.6322
Epoch 8/50
240/240 [==============================] - 1s 3ms/step - loss: 42.1698
Epoch 9/50
240/240 [==============================] - 1s 2ms/step - loss: 39.3778
Epoch 10/50
240/240 [==============================] - 1s 2ms/step - loss: 38.1268
Epoch 11/50
240/240 [==============================] - 1s 2ms/step - loss: 35.9988
Epoch 12/50
240/240 [==============================] - 1s 2ms/step - loss: 35.6356
Epoch 13/50


## Predicting the results of the Test set

In [21]:
y_pred = ann.predict(x_test)   # Predicting test data
y_pred

60/60 [==============================] - 0s 2ms/step


array([[430.94217],
       [461.8091 ],
       [465.22913],
       ...,
       [472.44016],
       [439.61502],
       [458.6007 ]], dtype=float32)

In [22]:
y_test = y_test.reshape(len(y_test),1)
y_test

array([[431.23],
       [460.01],
       [461.14],
       ...,
       [473.26],
       [438.  ],
       [463.28]])

In [23]:
np.concatenate((y_pred,y_test),1)    # Now we can compare the test data and predicted data it is showing approximately same value in both 

array([[430.94216919, 431.23      ],
       [461.80911255, 460.01      ],
       [465.22912598, 461.14      ],
       ...,
       [472.44015503, 473.26      ],
       [439.61502075, 438.        ],
       [458.60070801, 463.28      ]])